export const ADD_RECIPE = 'ADD_RECIPE';
export const DELETE_TODO = 'DELETE_TODO';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_USER_PRODUCTS_SUCCESS = 'FETCH_USER_PRODUCTS_SUCCESS';
export const FETCH_USER_PRODUCT_INFO = 'FETCH_USER_PRODUCT_INFO';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN';
export const GO_TO_NEXT_PAGE = 'GO_TO_NEXT_PAGE';
export const ADD_USER_SELECTION = 'ADD_USER_SELECTION';
export const REMOVE_USER_SELECTION = 'REMOVE_USER_SELECTION';
export const POST_USER_RECIPE_BEGIN = 'POST_USER_RECIPE';
export const POST_USER_RECIPE_SUCCESS = 'POST_USER_RECIPE_SUCCESS';
export const POST_USER_RECIPE_FAILURE = 'POST_USER_RECIPE_FAILURE';

export const RESET_PAGE_NR = 'RESET_PAGE_NR';

//Getting the user recipes id
export const FETCH_SAVED_RECIPES_BEGIN = 'FETCH_SAVED_RECIPES_BEGIN';
export const FETCH_SAVED_RECIPES_SUCCESS = 'FETCH_SAVED_RECIPES_SUCCESS';
export const FETCH_SAVED_RECIPES_FAILURE = 'FETCH_SAVED_RECIPES_FAILURE';

//Getting recipes from id
export const FETCH_RECIPE_INFO_BEGIN = 'FETCH_RECIPE_INFO_BEGIN';
export const FETCH_RECIPE_INFO_SUCCESS = 'FETCH_RECIPE_INFO_SUCCESS';
export const FETCH_RECIPE_INFO_FAILURE = 'FETCH_RECIPE_INFO_FAILURE';

//For loading
export const START_LOADING = 'START_LOADING';
